"""recurring templates

Revision ID: 166b47e18a3a
Revises: 3fec8dd457b6
Create Date: 2026-10-03 01:19:02.413827

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "166b47e18a3a"
down_revision: str | Sequence[str] | None = "3fec8dd457b6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "recurring_templates",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("type", sa.String(length=10), nullable=False),
        sa.Column("amount", sa.BigInteger(), nullable=False),
        sa.Column("account_id", sa.Uuid(), nullable=False),
        sa.Column("to_account_id", sa.Uuid(), nullable=True),
        sa.Column("category_id", sa.Uuid(), nullable=True),
        sa.Column("description", sa.String(length=200), nullable=True),
        sa.Column("day_of_month", sa.SmallInteger(), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column("next_run_date", sa.Date(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(type = 'transfer' AND to_account_id IS NOT NULL AND category_id IS NULL AND to_account_id <> account_id) OR (type <> 'transfer' AND to_account_id IS NULL AND category_id IS NOT NULL)",
            name=op.f("ck_recurring_templates_shape_valid"),
        ),
        sa.CheckConstraint(
            "type IN ('income', 'expense', 'transfer')",
            name=op.f("ck_recurring_templates_type_valid"),
        ),
        sa.CheckConstraint("amount > 0", name=op.f("ck_recurring_templates_amount_positive")),
        sa.CheckConstraint(
            "day_of_month BETWEEN 1 AND 31", name=op.f("ck_recurring_templates_day_valid")
        ),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.id"],
            name=op.f("fk_recurring_templates_account_id_accounts"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["categories.id"],
            name=op.f("fk_recurring_templates_category_id_categories"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["to_account_id"],
            ["accounts.id"],
            name=op.f("fk_recurring_templates_to_account_id_accounts"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_recurring_templates_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_recurring_templates")),
    )
    op.create_index(
        op.f("ix_recurring_templates_user_id"), "recurring_templates", ["user_id"], unique=False
    )
    op.add_column("transactions", sa.Column("recurring_template_id", sa.Uuid(), nullable=True))
    op.create_unique_constraint(
        "uq_transactions_template_date", "transactions", ["recurring_template_id", "date"]
    )
    op.create_foreign_key(
        op.f("fk_transactions_recurring_template_id_recurring_templates"),
        "transactions",
        "recurring_templates",
        ["recurring_template_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_transactions_recurring_template_id_recurring_templates"),
        "transactions",
        type_="foreignkey",
    )
    op.drop_constraint("uq_transactions_template_date", "transactions", type_="unique")
    op.drop_column("transactions", "recurring_template_id")
    op.drop_index(op.f("ix_recurring_templates_user_id"), table_name="recurring_templates")
    op.drop_table("recurring_templates")
    # ### end Alembic commands ###
