"""savings rules

Revision ID: 3fec8dd457b6
Revises: 965c8bda44e3
Create Date: 2026-10-03 01:14:59.656561

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3fec8dd457b6"
down_revision: str | Sequence[str] | None = "965c8bda44e3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "savings_rules",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("mode", sa.String(length=10), nullable=False),
        sa.Column("value", sa.BigInteger(), nullable=False),
        sa.Column("trigger_category_id", sa.Uuid(), nullable=False),
        sa.Column("target_account_id", sa.Uuid(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "mode IN ('percent', 'fixed')", name=op.f("ck_savings_rules_mode_valid")
        ),
        sa.CheckConstraint("value > 0", name=op.f("ck_savings_rules_value_positive")),
        sa.ForeignKeyConstraint(
            ["target_account_id"],
            ["accounts.id"],
            name=op.f("fk_savings_rules_target_account_id_accounts"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["trigger_category_id"],
            ["categories.id"],
            name=op.f("fk_savings_rules_trigger_category_id_categories"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_savings_rules_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_savings_rules")),
        sa.UniqueConstraint("user_id", name=op.f("uq_savings_rules_user_id")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("savings_rules")
    # ### end Alembic commands ###
